# Site settings
title: ledell
email: oss@ledell.org
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Erin LeDell.
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://ledell.github.io
twitter_username: ledell
github_username:  ledell

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


